# services:
#   backend:
#     build: ./backend
#     container_name: clouddeployx-backend
#     ports:
#       - "5000:5000"

#   frontend:
#     build: ./frontend
#     container_name: clouddeployx-frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend




version: "3.9"

services:

  mongodb:
    image: mongo:7
    container_name: clouddeployx-mongodb
    restart: always

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db


  backend:
    build: ./backend
    container_name: clouddeployx-backend

    restart: always

    ports:
      - "5000:5000"

    depends_on:
      - mongodb

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - MONGO_URI=mongodb://mongodb:27017/clouddeployx
  #   env_file:
  #     - ./backend/.env
  # #the above 2 line is for aws 

  frontend:
    build: ./frontend
    container_name: clouddeployx-frontend

    restart: always

    ports:
      - "3000:3000"

    depends_on:
      - backend


volumes:
  mongo_data: